using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TimeSliderSyncModel{

    [RealtimeProperty(1, true, true)]
    private int _timeSliderYear;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TimeSliderSyncModel : RealtimeModel {
    public int timeSliderYear {
        get {
            return _timeSliderYearProperty.value;
        }
        set {
            if (_timeSliderYearProperty.value == value) return;
            _timeSliderYearProperty.value = value;
            InvalidateReliableLength();
            FireTimeSliderYearDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TimeSliderSyncModel model, T value);
    public event PropertyChangedHandler<int> timeSliderYearDidChange;
    
    public enum PropertyID : uint {
        TimeSliderYear = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _timeSliderYearProperty;
    
    #endregion
    
    public TimeSliderSyncModel() : base(null) {
        _timeSliderYearProperty = new ReliableProperty<int>(1, _timeSliderYear);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _timeSliderYearProperty.UnsubscribeCallback();
    }
    
    private void FireTimeSliderYearDidChange(int value) {
        try {
            timeSliderYearDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _timeSliderYearProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _timeSliderYearProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.TimeSliderYear: {
                    changed = _timeSliderYearProperty.Read(stream, context);
                    if (changed) FireTimeSliderYearDidChange(timeSliderYear);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _timeSliderYear = timeSliderYear;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
